# %%
"""
Train a fresh Delphi model on synthetic subjects generated by
generate_synthetic_subjects.py, standalone from train.py.

Only the domains that script actually writes are available: sex, lifestyle,
diseases, death (no drugs/hla_alleles/genetic_pcs/rare_variants -- the model
never generates those on its own, see generate_synthetic_subjects.py's
docstring). Splits are a fresh random train/val/test partition over whatever
subject_ids are found under --tokens_dir: these synthetic IDs live outside
the real UKB cohort's fold files (data/transforms/subject_lists/), so
train.py's CV/fold machinery (utils.cv_utils.get_data_partitions) does not
apply to them and is intentionally not reused here.

Usage:
    python train_synthetic.py \\
        --tokens_dir data/transforms/tokens/synthetic \\
        --experiment_name synthetic-delphi \\
        --max_epochs 100 \\
        --compute_real_aucs

--compute_real_aucs evaluates the trained model's AUCs on REAL subjects
(a real UKB test fold, via utils.cv_utils.get_data_partitions), not on
synthetic ones -- the point of training on synthetic data is to see whether
it generalizes to the real disease distribution, so evaluating on more
synthetic data wouldn't answer that. This works because
generate_synthetic_subjects.py copies each domain's real tokenizer.yaml
verbatim into the synthetic output, so token_ids for sex/lifestyle/diseases/
death are identical between the synthetic training data and the real
evaluation data -- no vocab mismatch.
"""
import argparse
import logging
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

DEVICE = os.getenv("DEVICE", "cuda" if torch.cuda.is_available() else "cpu")
if (DELPHI_DIR := Path(__file__).resolve().parent) not in sys.path:
    sys.path.insert(0, str(DELPHI_DIR))

from data.dataset import DelphiDataset, DelphiCollateFn, AgeSampler, FlexibleDataLoader, DataModule
from delphi.model import Delphi, DelphiConfig, DomainConfig
from delphi.optim import OptimConfig, configure_optimizers
from utils.trainer import MLFlowLogger, Trainer
from utils.cv_utils import get_data_partitions
from utils import setup_mlflow
from train import _compile_model  # reuse cache-aware torch.compile wrapper
from auc.aucs import evaluate_aucs

REAL_TOKENS_ROOT = DELPHI_DIR / "data" / "transforms" / "tokens"
REAL_FOLDS_DIR = DELPHI_DIR / "data" / "transforms" / "subject_lists"
AUC_BLOCK_SIZE = 128  # evaluate_aucs needs a fixed T across batches (see train.py)

SYNTHETIC_DOMAINS = ("sex", "lifestyle", "diseases", "death")


def build_domain_config(tokens_dir: Path) -> dict:
    """Domain config for the 4 domains generate_synthetic_subjects.py writes.
    Mirrors config/domain_config_default.yaml's settings for these domains,
    but with `path` pointing directly (as an absolute path) at tokens_dir --
    bypassing the usual root/tokens/<path> YAML resolution, since this
    synthetic folder isn't necessarily under data/transforms/tokens/.
    """
    return {
        "sex": DomainConfig(
            projector="embed", path=str(tokens_dir / "sex"), at_birth=True,
        ),
        "lifestyle": DomainConfig(
            projector="embed", path=str(tokens_dir / "lifestyle"),
            dropout_mode="token", dropout_rate=0.1,
            age_jitter=True, age_jitter_min=-7300, age_jitter_max=14610,
        ),
        "diseases": DomainConfig(
            projector="embed", path=str(tokens_dir / "diseases"),
            predict=True, no_repeat=True, dropout_mode="token", dropout_rate=0.1,
        ),
        "death": DomainConfig(
            projector="embed", path=str(tokens_dir / "death"), predict=True,
        ),
        "padding": DomainConfig(projector="embed"),
        "no_event": DomainConfig(projector="embed", predict=False),
    }


def split_subjects(tokens_dir: Path, val_frac: float, test_frac: float, seed: int, n_subjects_debug=None):
    """Fresh random train/val/test split over the synthetic subject_ids.

    Every synthetic subject has exactly one 'sex' token (it's at_birth), so
    that domain's tokens.csv is the cheapest place to read the full
    subject_id list from.

    n_subjects_debug: if given, subsample the pool down to this many subjects
    (from the already-generated tokens_dir) before splitting -- for a quick
    sanity run over a large pre-generated cohort, without regenerating
    anything smaller.
    """
    subject_ids = pd.read_csv(tokens_dir / "sex" / "tokens.csv")["subject_id"].unique()
    rng = np.random.default_rng(seed)
    subject_ids = rng.permutation(subject_ids)
    if n_subjects_debug is not None:
        subject_ids = subject_ids[:n_subjects_debug]
    n = len(subject_ids)
    n_val = int(n * val_frac)
    n_test = int(n * test_frac)
    val_ids = subject_ids[:n_val].tolist()
    test_ids = subject_ids[n_val:n_val + n_test].tolist()
    train_ids = subject_ids[n_val + n_test:].tolist()
    return train_ids, val_ids, test_ids


def get_cli_args():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)

    parser.add_argument("--tokens_dir", "--tokens-dir", dest="tokens_dir", required=True, type=Path,
                        help="Folder written by generate_synthetic_subjects.py "
                             "(must contain sex/, lifestyle/, diseases/, death/ subfolders)")

    parser.add_argument("--attention_scheme", "--attention-scheme", dest="attention_scheme",
                        default="all:causal(mask_ties=True)")
    parser.add_argument("--n_layer", "--n-layer", dest="n_layer", default=12, type=int)
    parser.add_argument("--n_head", "--n-head", dest="n_head", default=6, type=int)
    parser.add_argument("--n_embd", "--n-embd", dest="n_embd", default=120, type=int)
    parser.add_argument("--block_size", "--block-size", dest="block_size", default=512, type=int)
    parser.add_argument("--batch_size", "--batch-size", dest="batch_size", default=64, type=int)
    parser.add_argument("--eval_batch_size", "--eval-batch-size", dest="eval_batch_size", default=256, type=int)
    parser.add_argument("--num_workers", "--num-workers", dest="num_workers", default=4, type=int)
    parser.add_argument("--token_dropout", "--token-dropout", dest="token_dropout", default=0.1, type=float)
    parser.add_argument("--no_event_token_rate", "--no-event-token-rate", dest="no_event_token_rate",
                        default=2.0, type=float)
    parser.add_argument("--no_event_token_insertion_mode", "--no-event-token-insertion-mode",
                        dest="no_event_token_insertion_mode", default="random")

    parser.add_argument("--val_frac", "--val-frac", dest="val_frac", default=0.1, type=float)
    parser.add_argument("--test_frac", "--test-frac", dest="test_frac", default=0.1, type=float)
    parser.add_argument("--n_subjects_debug", "--n-subjects-debug", dest="n_subjects_debug", default=None, type=int,
                        help="Subsample the synthetic cohort under --tokens_dir down to this many "
                             "subjects before splitting (for a quick sanity run over an "
                             "already-generated large cohort, without regenerating anything).")
    parser.add_argument("--seed", default=142, type=int)

    parser.add_argument("--learning_rate", "--learning-rate", "--lr", dest="lr", default=1e-4, type=float)
    parser.add_argument("--min_lr", "--min-lr", dest="min_lr", default=None, type=float)
    parser.add_argument("--weight_decay", "--weight-decay", dest="weight_decay", default=1e-1, type=float)
    parser.add_argument("--grad_clip", "--grad-clip", dest="grad_clip", default=1.0, type=float)
    parser.add_argument("--schedule", default="cosine", choices=["cosine", "constant"])
    parser.add_argument("--warmup_iters", "--warmup-iters", dest="warmup_iters", default=2000, type=int)
    parser.add_argument("--lr_decay_iters", "--lr-decay-iters", dest="lr_decay_iters", default=10000, type=int)

    parser.add_argument("--max_epochs", "--max-epochs", dest="max_epochs", default=1000, type=int)
    parser.add_argument("--min_epochs", "--min-epochs", dest="min_epochs", default=0, type=int)
    parser.add_argument("--patience", default=20, type=int)
    parser.add_argument("--checkpoint_every", "--checkpoint-every", dest="checkpoint_every", default=None, type=int)

    parser.add_argument("--log_loss_per_disease", "--log-loss-per-disease", dest="log_loss_per_disease",
                        default=False, action="store_true")
    parser.add_argument("--baseline_incidence_path", "--baseline-incidence-path", dest="baseline_incidence_path",
                        default=None, type=str,
                        help="Age-sex stratified real disease incidence parquet, for relative CCE logging "
                             "(e.g. config/disease_incidence.parquet) -- see utils/trainer.py.")

    parser.add_argument("--use_amp", "--use-amp", "--amp", dest="use_amp", default=False, action="store_true")
    parser.add_argument("--no-compile", "--no_compile", dest="no_compile", default=False, action="store_true")
    parser.add_argument("--no_rich", "--no-rich", dest="no_rich", action="store_true", default=False)

    parser.add_argument("--compute_real_aucs", "--compute-real-aucs", dest="compute_real_aucs",
                        default=False, action="store_true",
                        help="After training, evaluate AUCs on a REAL UKB test fold "
                             "(not on synthetic subjects) — see module docstring.")
    parser.add_argument("--real_test_fold", "--real-test-fold", dest="real_test_fold", default=1, type=int,
                        help="Which real CV fold's test split to evaluate on (see utils.cv_utils.get_data_partitions)")

    parser.add_argument("--experiment_name", "--experiment-name", "-x", dest="experiment_name",
                        default="synthetic-delphi")
    parser.add_argument("--run_name", "--run-name", dest="run_name", default=None)

    parser.add_argument("--dryrun", "--dry-run", dest="dry_run", action="store_true", default=False)

    return parser.parse_args()


def get_dataloaders(domain_cfg, model, tokens_dir, args):
    train_ids, val_ids, test_ids = split_subjects(
        tokens_dir, args.val_frac, args.test_frac, args.seed, n_subjects_debug=args.n_subjects_debug
    )
    logging.info("Synthetic split: %d train / %d val / %d test", len(train_ids), len(val_ids), len(test_ids))

    root = str(DELPHI_DIR / "data" / "transforms")  # inert here: every domain path above is absolute

    dataset_kwargs = dict(
        root=root, domains_cfg=domain_cfg, domain_to_int=model.domain_to_int,
        block_size=args.block_size, required_domains=["sex"],
        no_event_token_rate=args.no_event_token_rate,
        no_event_insertion_mode=args.no_event_token_insertion_mode,
        age_domains=["diseases", "death"],
    )
    train_dataset = DelphiDataset(subjects=train_ids, **dataset_kwargs)
    valid_dataset = DelphiDataset(subjects=val_ids, **dataset_kwargs)
    test_dataset = DelphiDataset(subjects=test_ids, **dataset_kwargs)

    age_sampler = AgeSampler(
        insertion_mode=args.no_event_token_insertion_mode,
        token_rate=args.no_event_token_rate,
        seed=args.seed,
    )

    domain_dropout = {
        model.domain_to_int[dname]: (cfg.dropout_mode, cfg.dropout_rate, cfg.token_dropout_rate, cfg.parent or dname)
        for dname, cfg in domain_cfg.items()
        if cfg.dropout_mode is not None and cfg.dropout_rate > 0
    }
    age_jitter = {
        model.domain_to_int[dname]: (cfg.age_jitter_min, cfg.age_jitter_max)
        for dname, cfg in domain_cfg.items()
        if cfg.age_jitter and dname in model.domain_to_int
    }

    collate_kwargs = dict(
        age_sampler=age_sampler, block_size=args.block_size, domain_to_int=model.domain_to_int,
        domain_offsets=model.domain_offsets, padding_domain_id=model.domain_to_int["padding"],
        no_event_domain_id=model.domain_to_int["no_event"], continuous_domains={},
        domain_dropout=domain_dropout,
    )
    train_collate = DelphiCollateFn(**collate_kwargs, age_jitter=age_jitter, training=True)
    eval_collate = DelphiCollateFn(**collate_kwargs, training=False)

    train_kwargs = dict(batch_size=args.batch_size, num_workers=args.num_workers, pin_memory=True)
    eval_kwargs = dict(batch_size=args.eval_batch_size, num_workers=args.num_workers, pin_memory=True)

    train_loader = FlexibleDataLoader(train_dataset, shuffle=True, collate_fn=train_collate, **train_kwargs)
    valid_loader = FlexibleDataLoader(valid_dataset, shuffle=False, collate_fn=eval_collate, **eval_kwargs)
    test_loader = FlexibleDataLoader(test_dataset, shuffle=False, collate_fn=eval_collate, **eval_kwargs)

    return DataModule(train_loader, valid_loader, test_loader)


def build_real_eval_loader(model, real_test_fold, eval_batch_size, num_workers):
    """Real-data test DataLoader for evaluate_aucs, over the same 4 domains
    the synthetic-trained model has embeddings for. Vocab is identical to
    the synthetic training data (see module docstring), so this model can
    be run directly on it without any remapping.
    """
    real_domain_cfg = build_domain_config(REAL_TOKENS_ROOT)
    _, _, real_test_ids = get_data_partitions(str(REAL_FOLDS_DIR), fold=real_test_fold)

    real_test_dataset = DelphiDataset(
        root=str(DELPHI_DIR / "data" / "transforms"), domains_cfg=real_domain_cfg,
        domain_to_int=model.domain_to_int, block_size=AUC_BLOCK_SIZE,
        subjects=real_test_ids, required_domains=["sex"],
        age_domains=["diseases", "death"],
    )
    eval_collate = DelphiCollateFn(
        age_sampler=AgeSampler(insertion_mode="random", token_rate=2.0, seed=0),
        block_size=AUC_BLOCK_SIZE, domain_to_int=model.domain_to_int,
        domain_offsets=model.domain_offsets, padding_domain_id=model.domain_to_int["padding"],
        no_event_domain_id=model.domain_to_int["no_event"], continuous_domains={},
        training=False,
    )
    from torch.utils.data import DataLoader
    return DataLoader(
        real_test_dataset, batch_size=eval_batch_size, shuffle=False,
        num_workers=num_workers, pin_memory=True, collate_fn=eval_collate,
    )


def main():
    args = get_cli_args()
    setup_mlflow()

    tokens_dir = args.tokens_dir.resolve()
    for d in SYNTHETIC_DOMAINS:
        tokens_csv = tokens_dir / d / "tokens.csv"
        if not tokens_csv.exists():
            raise FileNotFoundError(
                f"{tokens_csv} not found -- run generate_synthetic_subjects.py "
                f"with --output_dir {tokens_dir} first"
            )

    domain_cfg = build_domain_config(tokens_dir)

    delphi_config = DelphiConfig(
        n_layer=args.n_layer, n_head=args.n_head, n_embd=args.n_embd,
        domains=domain_cfg, attention_scheme=args.attention_scheme,
        token_dropout=args.token_dropout, block_size=args.block_size,
        no_event_token_rate=args.no_event_token_rate,
        no_event_token_insertion_mode=args.no_event_token_insertion_mode,
        seed=args.seed,
    )

    if args.dry_run:
        print(delphi_config)
        sys.exit(0)

    model = Delphi(delphi_config).to(DEVICE)
    model = _compile_model(model, disable=args.no_compile)

    dataloaders = get_dataloaders(domain_cfg, model, tokens_dir, args)

    optim_config = OptimConfig(
        learning_rate=args.lr,
        min_lr=args.min_lr if args.min_lr is not None else args.lr / 10,
        weight_decay=args.weight_decay,
        grad_clip=args.grad_clip,
        schedule=args.schedule,
        warmup_iters=args.warmup_iters,
        lr_decay_iters=args.lr_decay_iters,
    )
    optimizer, scheduler = configure_optimizers(model=model, cfg=optim_config, device_type=DEVICE)

    logger = MLFlowLogger(experiment_name=args.experiment_name, run_name=args.run_name)
    logger.log_run_metadata(cwd=DELPHI_DIR)

    n_params = sum(p.numel() for p in model.parameters())
    logged_params = {
        "tokens_dir": str(tokens_dir),
        "synthetic": True,
        "n_subjects_debug": args.n_subjects_debug,
        "val_frac": args.val_frac,
        "test_frac": args.test_frac,
        "batch_size": args.batch_size,
        "learning_rate": args.lr,
        "seed": args.seed,
        "optim_config": optim_config,
        "max_epochs": args.max_epochs,
        "min_epochs": args.min_epochs,
        "patience": args.patience,
        "n_params": n_params,
    }

    dataloaders.log_info()
    logged_params["n_train"] = dataloaders.n_train
    logged_params["n_val"] = dataloaders.n_val
    logged_params["n_test"] = dataloaders.n_test

    trainer = Trainer(
        model, dataloaders,
        optimizer, scheduler,
        log_loss_per_disease=args.log_loss_per_disease,
        baseline_incidence_path=args.baseline_incidence_path,
        checkpoint_every=args.checkpoint_every,
        logger=logger,
        mlflow_params=logged_params,
        use_tqdm=args.no_rich,
        use_amp=args.use_amp,
        use_rich=not args.no_rich,
        optim_config=optim_config,
    )

    trainer.train(max_epochs=args.max_epochs, min_epochs=args.min_epochs, patience=args.patience)

    if args.compute_real_aucs:
        model.eval()
        real_test_loader = build_real_eval_loader(
            model, args.real_test_fold, args.eval_batch_size, args.num_workers
        )
        auc_df = evaluate_aucs(
            model, real_test_loader, block_size=AUC_BLOCK_SIZE,
            run_id=logger.active_run.info.run_id, n_jobs=8, logger=logger,
            output_file="aucs_real.csv",
        )
        logging.info("Real-data AUCs (model trained on synthetic data):\n%s", auc_df)


if __name__ == "__main__":
    main()
