"""
Aggregate delta-logit .pkl files produced by individual sarray_params jobs
(one per allele pair) into a single summary TSV ready for the Epistasis tab
of the Streamlit app.

Each pkl is named:
    {disease_id}__{allele_id_a}-{allele_id_b}__{sex_label}.pkl

Pair metadata (allele names, loci, pair_type, co-carrier freq) is read from
the pairs_{disease_id}.meta.tsv file generated by --generate_pairs.

Usage:
    python shap/compute_pvalues_table_pairs.py \\
        --pkl_dir  shap/output_delta_logit \\
        --meta_tsv shap/pairs_713.meta.tsv \\
        --output   shap/output_delta_logit/713__scan_pairs__both_sexes.tsv \\
        [--min_n 10]

    # Process multiple diseases / sex labels at once:
    python shap/compute_pvalues_table_pairs.py \\
        --pkl_dir  shap/output_delta_logit \\
        --meta_dir shap                    \\  # searches for pairs_*.meta.tsv here
        --output   shap/output_delta_logit/summary_pairs.tsv

Arguments:
    --pkl_dir   Directory containing the .pkl files (searched recursively).
    --meta_tsv  Path to a single pairs_*.meta.tsv file.
    --meta_dir  Directory to search for pairs_*.meta.tsv files (alternative to --meta_tsv).
    --output    Output TSV path (default: <pkl_dir>/summary_pairs.tsv).
    --min_n     Minimum number of delta values to compute Wilcoxon (default: 10).
    --sex       If given, restrict to pkl files with this sex label (e.g. both_sexes).
"""

import argparse
import pickle
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import yaml
from scipy import stats

DELPHI_DIR = Path("/nfs/research/birney/users/bonazzola/repos/delphis/delphi-refactor")

# Filename pattern: {disease_id}__{a_id}-{b_id}__{sex_label}.pkl
_PKL_RE = re.compile(r"^(\d+)__(\d+)-(\d+)__(.+)\.pkl$")


def load_meta(meta_tsv: Path) -> pd.DataFrame:
    df = pd.read_csv(meta_tsv, sep="\t")
    # Normalise column names — generator writes 'allele_id' and 'allele_id_b'
    rename = {}
    if "allele_id" in df.columns and "allele_id_a" not in df.columns:
        rename["allele_id"] = "allele_id_a"
    df = df.rename(columns=rename)
    df["allele_id_a"] = df["allele_id_a"].astype(int)
    df["allele_id_b"] = df["allele_id_b"].astype(int)
    return df


def build_meta_index(meta_df: pd.DataFrame) -> dict:
    """Return {(a_id, b_id): row_dict} for fast lookup."""
    idx = {}
    for _, row in meta_df.iterrows():
        idx[(int(row["allele_id_a"]), int(row["allele_id_b"]))] = row.to_dict()
        # Also index the reverse pair so lookup works regardless of order
        idx[(int(row["allele_id_b"]), int(row["allele_id_a"]))] = row.to_dict()
    return idx


def load_disease_tokenizer():
    path = DELPHI_DIR / "data/transforms/tokens/diseases/tokenizer.yaml"
    return list(yaml.safe_load(open(path)))


def process_pkl(pkl_path: Path, meta_index: dict, disease_tok: list, min_n: int) -> dict | None:
    m = _PKL_RE.match(pkl_path.name)
    if not m:
        return None

    disease_id = int(m.group(1))
    a_id       = int(m.group(2))
    b_id       = int(m.group(3))
    sex_label  = m.group(4)

    try:
        with open(pkl_path, "rb") as f:
            data = pickle.load(f)
    except Exception as e:
        print(f"  SKIP (load error): {pkl_path} — {e}", file=sys.stderr)
        return None

    delta = np.asarray(data["delta"]).ravel()
    n = len(delta)

    if n < min_n:
        p = float("nan")
    else:
        try:
            p = float(stats.wilcoxon(delta).pvalue)
        except Exception:
            p = float("nan")

    disease_name = (
        disease_tok[disease_id] if disease_id < len(disease_tok) else str(disease_id)
    )

    meta = meta_index.get((a_id, b_id), {})
    # Infer pair_type from meta or from IDs
    pair_type = meta.get("pair_type", "hom" if a_id == b_id else "unknown")

    return {
        "disease_id":      disease_id,
        "disease_name":    disease_name,
        "allele_id_a":     a_id,
        "allele_id_b":     b_id,
        "allele_name_a":   meta.get("allele_name_a", str(a_id)),
        "allele_name_b":   meta.get("allele_name_b", str(b_id)),
        "locus_a":         meta.get("locus_a", ""),
        "locus_b":         meta.get("locus_b", ""),
        "pair_type":       pair_type,
        "n_cocarriers":    meta.get("n_cocarriers", ""),
        "cocarrier_freq":  meta.get("cocarrier_freq", ""),
        "sex":             sex_label,
        "n_cases":         n,
        "mean_delta":      float(np.mean(delta)) if n > 0 else float("nan"),
        "median_delta":    float(np.median(delta)) if n > 0 else float("nan"),
        "p_wilcoxon":      p,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--pkl_dir", type=Path, required=True,
                        help="Directory containing {disease_id}__{a}-{b}__{sex}.pkl files.")
    parser.add_argument("--meta_tsv", type=Path, default=None,
                        help="Path to a single pairs_*.meta.tsv file.")
    parser.add_argument("--meta_dir", type=Path, default=None,
                        help="Directory to search for pairs_*.meta.tsv files.")
    parser.add_argument("--output", type=Path, default=None,
                        help="Output TSV path (default: <pkl_dir>/summary_pairs.tsv).")
    parser.add_argument("--min_n", type=int, default=10,
                        help="Minimum delta count for Wilcoxon test (default: 10).")
    parser.add_argument("--sex", type=str, default=None,
                        help="Restrict to this sex label (e.g. both_sexes).")
    args = parser.parse_args()

    # --- Load meta TSV(s) ---
    meta_index: dict = {}
    if args.meta_tsv:
        meta_index.update(build_meta_index(load_meta(args.meta_tsv)))
    if args.meta_dir:
        for f in sorted(args.meta_dir.glob("pairs_*.meta.tsv")):
            meta_index.update(build_meta_index(load_meta(f)))
    if not meta_index:
        print(
            "Warning: no meta TSV loaded — allele names and loci will be missing.\n"
            "Pass --meta_tsv or --meta_dir to include them.",
            file=sys.stderr,
        )

    # --- Find pkl files ---
    pkl_files = sorted(args.pkl_dir.rglob("*.pkl"))
    # Keep only pair-format filenames (two IDs separated by '-')
    pkl_files = [p for p in pkl_files if _PKL_RE.match(p.name)]
    if args.sex:
        pkl_files = [p for p in pkl_files if f"__{args.sex}.pkl" in p.name]

    print(f"Found {len(pkl_files)} pkl files matching pair pattern.")
    if not pkl_files:
        print("No files to process. Exiting.")
        return

    disease_tok = load_disease_tokenizer()

    rows = []
    for pkl_path in pkl_files:
        row = process_pkl(pkl_path, meta_index, disease_tok, args.min_n)
        if row is not None:
            rows.append(row)

    if not rows:
        print("No valid rows produced.")
        return

    df = (
        pd.DataFrame(rows)
        .sort_values(["disease_id", "sex", "locus_a", "locus_b", "mean_delta"],
                     ascending=[True, True, True, True, False])
        .reset_index(drop=True)
    )

    output = args.output or args.pkl_dir / "summary_pairs.tsv"
    output.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output, sep="\t", index=False)
    print(f"Saved {len(df)} rows → {output}")
    print(df.head(20).to_string(index=False))


if __name__ == "__main__":
    main()
