diseases:
  projector: embed
  path: diseases
  predict: true
  no_repeat: true
  dropout_mode: token
  dropout_rate: 0.1
  group: core

death:
  projector: embed
  path: death
  predict: true
  group: core

cv_drugs:
  projector: embed
  path: cv_drugs
  predict: true
  group: drugs

ns_drugs:
  projector: embed
  path: ns_drugs
  predict: true
  group: drugs

lifestyle:
  projector: embed
  path: lifestyle
  dropout_mode: token
  dropout_rate: 0.1
  age_jitter: true
  age_jitter_min: -14610   # -40 years in days
  age_jitter_max: 7300   # +20 years in days
  group: core

hla_alleles:
  projector: embed
  path: hla_alleles
  at_birth: true
  # group: hla
  # dropout_mode: block   # drop the entire HLA block with probability dropout_rate
  # dropout_rate: 0.1

sex:
  projector: embed
  path: sex
  at_birth: true
  group: core

rare_variants:
  projector: embed
  path: rare_variants
  at_birth: true

genetic_pcs:
  type: continuous
  projector: linear
  path: genetic_pcs
  at_birth: true
  input_size: 40
  n_latent_tokens: 5

